
name: CI Pipeline Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true

    - run: npm ci
    - run: git config --global user.name "Automation"
    - run: git config --global user.email "Automation@ahriana.dev"
    - run: npm version ${{ github.event.release.tag_name }}
    - run: npm run build
    - run: npm run publish:dist --tag ${{ github.event.release.target_commitish }}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
